[project]
name = "cricket-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-genai>=1.26.0",
    "opencv-python",
    "moviepy",
    "google-generativeai>=0.8.5",
    "openai>=1.97.1",
]
